site_name: "rapidae"
site_description: "Rapidae is a Python library specialized in simplifying the creation and experimentation of autoencoder models. With a focus on ease of use, Rapidae allows users to explore and develop autoencoder models in an efficient and straightforward manner."
site_url: "https://rapidae.readthedocs.io/en/latest/"
repo_url: "https://github.com/NahuelCostaCortez/rapidae"
repo_name: "NahuelCostaCortez/rapidae"
site_dir: "site"
watch: [mkdocs.yml, README.md, src/rapidae]
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
    - Overview: index.md
    - Examples: examples.md
    #- Examples: 
    #- Recipes: recipes.md
    - API Reference: reference/
      #- conf: reference/rapidae/conf/
      #- data: 
      #  - reference/data.md
      #  - datasets: reference/rapidae/data/datasets/
      #  - preprocessing: reference/rapidae/data/preprocessing/
      #  - utils: reference/rapidae/data/utils/
    - Changelog: changelog.md
    - License: license.md
  #- FAQ: faq.md

repo_url: https://github.com/NahuelCostaCortez/rapidae/tree/main
repo_name: Open in Github

theme:
   name: material
   logo: logo.png
   favicon: logo.png
   icon:
    repo: fontawesome/brands/github
   features:
   - announce.dismiss
   - content.action.edit
   - content.action.view
   - content.code.annotate
   - content.code.copy
   - content.tooltips
   - navigation.footer
   - navigation.indexes
   - navigation.sections
   #- navigation.tabs
   - navigation.tabs.sticky
   - navigation.path
   - navigation.top
   - search.highlight
   - search.suggest
   - toc.follow
   palette:
   - media: "(prefers-color-scheme)"
     toggle:
      icon: material/brightness-auto
      name: Switch to light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: teal
     accent: purple
     toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: slate
     primary: black
     accent: lime
     toggle:
      icon: material/weather-night
      name: Switch to system preference

plugins:
- search
- gen-files:
    scripts:
    - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
        - https://mkdocstrings.github.io/autorefs/objects.inv
        paths: [src]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: table
          filters: ["!^_"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.snippets

